import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { McpAgent } from "agents/mcp";
import { PloiClient, VERSION, registerPloiTools } from "./tools.js";

// `Cloudflare.Env` (the Durable Object binding) is generated by `wrangler types`
// into worker-configuration.d.ts. Everything here is optional/multi-tenant: the
// Ploi token is supplied per-request by the caller, not stored on the Worker.
interface Env extends Cloudflare.Env {
  /** Optional override of the Ploi API base URL. */
  PLOI_API_BASE_URL?: string;
  /** Optional override of the outbound User-Agent header. */
  PLOI_USER_AGENT?: string;
}

/**
 * Per-session props. Bound when the MCP session is created (the `initialize`
 * request) from the incoming `Authorization` header and reused for the session.
 */
type Props = {
  /** The caller's Ploi.io API token, taken from `Authorization: Bearer <token>`. */
  ploiToken: string;
  /** Poke's per-user identifier (`X-Poke-User-Id`), kept for logging. */
  pokeUserId?: string;
};

export class PloiMcp extends McpAgent<Env, never, Props> {
  server = new McpServer({
    name: "ploi-mcp-server",
    version: VERSION,
  });

  async init(): Promise<void> {
    const apiToken = this.props?.ploiToken;

    if (!apiToken) {
      // Should never happen: the fetch handler rejects token-less requests with
      // a 401 before a session is ever created.
      throw new Error("Missing Ploi API token for this session.");
    }

    const client = new PloiClient({
      apiToken,
      baseUrl: this.env.PLOI_API_BASE_URL,
      userAgent: this.env.PLOI_USER_AGENT,
    });

    registerPloiTools(this.server, client);
  }
}

function bearerToken(request: Request): string | null {
  const header = request.headers.get("Authorization") ?? "";
  const match = /^Bearer\s+(.+)$/i.exec(header.trim());
  return match ? match[1].trim() : null;
}

function unauthorized(message: string): Response {
  return new Response(JSON.stringify({ error: "unauthorized", message }), {
    status: 401,
    headers: {
      "Content-Type": "application/json",
      "WWW-Authenticate": 'Bearer realm="ploi-mcp-server"',
    },
  });
}

export default {
  fetch(request: Request, env: Env, ctx: ExecutionContext): Response | Promise<Response> {
    const url = new URL(request.url);

    if (url.pathname === "/" || url.pathname === "/health") {
      return new Response("ploi-mcp-server ok\n", { status: 200 });
    }

    const isMcp = url.pathname === "/mcp" || url.pathname.startsWith("/mcp/");
    const isSse = url.pathname === "/sse" || url.pathname.startsWith("/sse/");

    if (!isMcp && !isSse) {
      return new Response("Not found", { status: 404 });
    }

    // The caller (e.g. Poke) supplies its own Ploi token as a bearer token.
    const ploiToken = bearerToken(request);
    if (!ploiToken) {
      return unauthorized("Provide your Ploi API token as `Authorization: Bearer <token>`.");
    }

    // Bind the token to the MCP session via props. `McpAgent` reads `ctx.props`
    // when it creates the session Durable Object on the initialize request.
    (ctx as ExecutionContext & { props?: Props }).props = {
      ploiToken,
      pokeUserId: request.headers.get("X-Poke-User-Id") ?? undefined,
    };

    // Streamable HTTP transport (recommended).
    if (isMcp) {
      return PloiMcp.serve("/mcp", { binding: "PloiMcp" }).fetch(request, env, ctx);
    }

    // SSE transport (legacy, kept for older MCP clients).
    return PloiMcp.serveSSE("/sse", { binding: "PloiMcp" }).fetch(request, env, ctx);
  },
};
